WITH AVAILABLE AS (
    SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND C.CAR_TYPE IN ('세단','SUV')
),
DISCOUNT AS (
    SELECT A.CAR_ID, A.CAR_TYPE, 
    ROUND((A.DAILY_FEE * 30 *(1 - P.DISCOUNT_RATE / 100))) AS FEE
    FROM AVAILABLE A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON A.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상'
)
SELECT *
FROM DISCOUNT
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC