-- 코드를 입력하세요
SELECT DATE_FORMAT(S.SALES_DATE,'%Y') AS YEAR, DATE_FORMAT(S.SALES_DATE,'%m') AS MONTH,
       COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, 
       ROUND(COUNT(DISTINCT U.USER_ID) / 
       (SELECT COUNT(*) 
        FROM USER_INFO 
        WHERE DATE_FORMAT(JOINED,'%Y') = '2021'),1) AS PUCHASED_RATIO
FROM ONLINE_SALE S 
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE DATE_FORMAT (JOINED,'%Y') = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH