WITH HISTORY AS (
    SELECT H.HISTORY_ID, C.CAR_TYPE, 
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
    C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID, 
ROUND(H.DAILY_FEE * H.DURATION * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON H.CAR_TYPE = P.CAR_TYPE AND
CASE 
    WHEN H.DURATION BETWEEN 7 AND 29 THEN '7일 이상'
    WHEN H.DURATION BETWEEN 30 AND 89 THEN '30일 이상'
    WHEN H.DURATION >= 90 THEN '90일 이상'
    ELSE NULL
END = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC