-- 코드를 입력하세요
WITH RECURSIVE HOURS(HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 
    FROM HOURS
    WHERE HOUR < 23)

SELECT H.HOUR AS HOUR, IFNULL(COUNT(A.DATETIME),0) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
ON H.HOUR = DATE_FORMAT(A.DATETIME,'%H')
GROUP BY H.HOUR
ORDER BY H.HOUR ASC