-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE H.HISTORY_ID IS NOT NULL AND C.CAR_TYPE = "세단" 
AND DATE_FORMAT(H.START_DATE, '%m') = '10'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC
